### ISSUE TITLE
给mac使用crossover运行的指个路

### ISSUE THREAD

**Issue by lszghcpp** [Alexander-Porter/idv-login#20]
https://github.com/lszghcpp/idv-login-for-mac

**Comment by Alexander-Porter** [comment]
身边没有测试设备，如果可用，可以提一个Pull Request吗？我把它合并到本项目。

**Comment by lszghcpp** [comment]
怎么说呢，能用，但不多。具体的表现是
确实能出来密码登录的那个窗口，但是输完密码点登录后本来是一个提示手机发验证码的（我的账号有风控），但是窗口是纯白的，whisky和crossover都试过不行
![Uploading 951718026902_.pic.jpg…]()
![Uploading 931718026763_.pic_hd.jpg…]()

**Comment by Alexander-Porter** [comment]
参考修改tls版本，多试几个
[这里](https://github.com/kevwo/tls1.2-server/blob/master/server.py)

**Comment by lszghcpp** [comment]
不应该是服务器问题吧，我那个项目就是fork的这里的然后把win才能用的一些东西改成了mac用的，没有修改逻辑呀（）

**Comment by lszghcpp** [comment]
不应该是服务器问题吧，我那个项目就是fork的这里的然后把win才能用的一些东西改成了mac用的，没有修改逻辑呀（）

**Comment by lszghcpp** [comment]
改了tlsv1.2还是白屏，想了几天感觉好像发现了问题但是还没试，感觉是不是因为wine没有安装证书的问题啊，不太清楚wine的网络那边是直接共享的本机的还是有一套单独的自己的东西

**Comment by lszghcpp** [comment]
或者说是我没有开对（）

**Comment by Alexander-Porter** [comment]
> 改了tlsv1.2还是白屏，想了几天感觉好像发现了问题但是还没试，感觉是不是因为wine没有安装证书的问题啊，不太清楚wine的网络那边是直接共享的本机的还是有一套单独的自己的东西

能出账号登录界面说明劫持已经成功了，也就说wine访问主机的443是可以的，而且根证书也能信任。

**Comment by lszghcpp** [comment]
怎么说呢，我已经成功了↓
![successful](https://img.picui.cn/free/2024/06/17/66701cc0f3542.jpg)
但是这个方法有些坎坷，如果你想了解的话加我q3578862627细说，总结一下这个方法就是偷梁换柱（）
