### ISSUE TITLE
linux版本的软件

### ISSUE THREAD

**Issue by LCHLCHLCHLCH** [Alexander-Porter/idv-login#21]
我试图在linux下运行本软件，但是在certutil那一步总是出错。求一个linux版本！（使用wine可以流畅运行第五人格PC）

**Comment by Alexander-Porter** [comment]
把那一步注释掉，换成input()阻塞程序。然后手动安装根证书文件。

**Comment by Alexander-Porter** [comment]
[考虑用这个](https://github.com/lszghcpp/idv-login-for-mac)
