### ISSUE TITLE
版本号错误

### ISSUE THREAD

**Issue by CrnEilns** [Alexander-Porter/idv-login#26]
在[Releases](https://github.com/Alexander-Porter/idv-login/releases)下的v5.2.4-stable
打开后程序内显示该版本为5.2.2-beta
![image](https://github.com/user-attachments/assets/542a2349-b89a-4d54-8b57-82811dd0e41d)

**Comment by Alexander-Porter** [comment]
是我的疏忽，会在5.3修复
