### ISSUE TITLE
渠道服登录失败

### ISSUE THREAD

**Issue by reganology** [Alexander-Porter/idv-login#32]
你好作者，我是用的是vivo手机，在手机浏览器上通过小米游戏商店网页下载的小米渠道服，使用工具扫码时提示不支持，请问是什么原因？
![image](https://github.com/user-attachments/assets/b1a791ae-d15a-48ca-9bcb-6f8c0c6d99b5)

**Comment by Alexander-Porter** [comment]
要在渠道服管理界面手动登录
