### ISSUE TITLE
5.3.1发版导致readme过期

### ISSUE THREAD

**Issue by i-yyi** [Alexander-Porter/idv-login#33]
建议：
看到CI中有加入BUILD_INFO的步骤，但是Readme里没有，并且现在不加BUILD_INFO会直接挂，感觉期望上是给出提示而不是直接挂。
1. 
在readme的手动打包中加入提示
'BUILD_INFO="MaunallyTrigger"' > src/buildinfo.py

2. 或者main的
```py
def cloudBuildInfo():
    try:
        from buildinfo import BUILD_INFO
        message=BUILD_INFO
    except:
        print("没有找到校验信息，请不要使用本工具，以免被盗号。")
    print(f"构建信息：{message}。如需校验此版本是否被篡改，请前往官方项目地址。")
```
异常格式应该处理一下，不然手动打包会直接因为 "print(f"构建信息：{message}。如需校验此版本是否被篡改，请前往官方项目地址。")"
导致cannot access local variable 'message'

**Comment by Alexander-Porter** [comment]
采用了第二种方案
