### ISSUE TITLE
华为，小米登录是否还未支持其他游戏

### ISSUE THREAD

**Issue by a1273822487** [Alexander-Porter/idv-login#34]
其他游戏，点小米华为登录都是显示执行失败

**Comment by Alexander-Porter** [comment]
请提交游戏apk下载链接供我适配。

**Comment by a1273822487** [comment]
[Uploading 华为小米明日之后.rar…]()

**Comment by a1273822487** [comment]
小米明日之后：https://game.xiaomi.com/game/62239760

**Comment by a1273822487** [comment]
华为明日之后：https://appgallery.huawei.com/app/C100245697

**Comment by bwdNB** [comment]
华为明日之后+1，恳请作者大大快点这个功能|•'-'•)و✧

**Comment by Alexander-Porter** [comment]
@a1273822487 @bwdNB 测试一下

**Comment by a1273822487** [comment]
小米还是不行
![屏幕截图 2024-08-18 204815](https://github.com/user-attachments/assets/4fb4fb05-c444-4960-9d33-6d87205fce37)

**Comment by Alexander-Porter** [comment]
> 小米还是不行 ![屏幕截图 2024-08-18 204815](https://private-user-images.githubusercontent.com/56152115/358906783-4fb4fb05-c444-4960-9d33-6d87205fce37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODY0MTksIm5iZiI6MTcyMzk4NjExOSwicGF0aCI6Ii81NjE1MjExNS8zNTg5MDY3ODMtNGZiNGZiMDUtYzQ0NC00OTYwLTlkMzMtNmQ4NzIwNWZjZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDEzMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmM2RlNTM5ZmE4ZjM5YTU2YzAyOWJkYWY5ZTgzNmM4ZjQ1ZTg0ZTRlZGNlNTAzYWNmZGExMTQ3YWJhZGFiNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.upH36WQIYedxcMxApNSEFG5Yp7clKbmMkgrIbm8S5fo)

操作不对，剪切板复制的网址有问题

**Comment by a1273822487** [comment]
好了，这个自动读取不了，一定要复制网址

**Comment by a1273822487** [comment]
华为好像切换不了账号

**Comment by bwdNB** [comment]
华为设为自动登录后不能自动“请在手机上点击确认”，打开网页点击登陆就可以

**Comment by bwdNB** [comment]
![Uploading image.png…]()1

**Comment by bwdNB** [comment]
![Uploading image.png…]()1
